name: locator
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  bloc_test: ^9.1.5
  cached_network_image: ^3.3.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  google_maps_flutter: ^2.5.0
  http: ^1.1.0
  intl: ^0.18.0
  json_annotation: ^4.8.1
  mocktail: ^1.0.1

dev_dependencies:
  build_runner: ^2.4.7
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  very_good_analysis: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
