name: Build Android Apk release

on:
  push:
    branches:
      - master

jobs:
  build_and_upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Set up sdkman and Gradle
        run: |
          curl -s "https://get.sdkman.io" | bash
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          sdk version
          sdk install gradle 8.1.1

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Fetch packages
        run: flutter pub get

      - name: Run tests
        run: flutter test

      - name: Generate and copy signing key
        run: |
          keytool -genkey -v -keystore keystore.jks -keyalg RSA -keysize 2048 -validity 10000 -storepass onspace -keypass onspace -dname "CN=Your Name, OU=Your Organizational Unit, O=Your Organization, L=Your City, ST=Your State, C=Your Country"
          cp keystore.jks android/app/

      - name: Build APK
        run: flutter build apk --flavor production --target lib/main_production.dart